plugins {
    id 'java'
    id 'application'
}

group = 'ru.kuzdikenov'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    implementation 'org.eclipse.jetty:jetty-server:11.0.20'
    implementation 'org.eclipse.jetty:jetty-servlet:11.0.20'
    implementation 'org.postgresql:postgresql:42.7.2'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.slf4j:slf4j-simple:2.0.12'
}

application {
    mainClass = 'ru.kuzdikenov.booking.Main'
}

tasks.named('run') {
    standardInput = System.in
}

tasks.named('jar') {
    manifest {
        attributes 'Main-Class': 'ru.kuzdikenov.booking.Main'
    }
}